### ISSUE TITLE
Protocol Error: Parse Issue "Expected a type" ->Compile Time Error

### ISSUE THREAD

**Issue by MMKK2016** [adamwaite/AJWDraggableDroppable#5]
Dear Friend,

While i try to import and use files into my project, get below error for all protocol files
Parse Issue "Expected a type" ->Compile Time Error

![screen shot 2016-01-01 at 10 17 43 pm](https://cloud.githubusercontent.com/assets/16510249/12071516/8f88dff8-b0d6-11e5-9652-fd380585eaff.png)

**Comment by adamwaite** [comment]
Not sure about that one. Looks like more of a project configuration issue rather than an issue with the lib so I'm going to close this. Is it complaining that CGPoint isn't defined? Perhaps CoreGraphics isn't included in the project or something...?
